services:
  backend:
    image: kipperdev/spring-boot-hello-world:1.0-amd64
    # build: ./nodejs-ping-pong
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: ./
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
