name: Continuous Integration

on: [pull_request, push]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Run install, build, and test
        run: |
          npm install
          npm run build
          npm run test
